apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: deglazed/server-demo:taxi
          env:
            - name: KAFKA_SERVER
              value: "kafka:9092"
            - name: LOCALSTACK_SERVER
              value: "http://localstack:4566"