from setuptools import setup, find_packages

setup(
    name='fl-platform',
    version='0.1.0',
    author='Radu Tanase',
    author_email='raducutanase@gmail.com',
    description='Federated Learning Platform for Human and Vehicle Mobility',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/DeGlazed/fl_platform',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    install_requires=[
        'boto3',
        'botocore',
        'certifi',
        'charset-normalizer',
        'filelock',
        'fsspec',
        'idna',
        'Jinja2',
        'jmespath',
        'kafka-python',
        'MarkupSafe',
        'mpmath',
        'networkx',
        'numpy',
        'nvidia-cublas-cu12',
        'nvidia-cuda-cupti-cu12',
        'nvidia-cuda-nvrtc-cu12',
        'nvidia-cuda-runtime-cu12',
        'nvidia-cudnn-cu12',
        'nvidia-cufft-cu12',
        'nvidia-cufile-cu12',
        'nvidia-curand-cu12',
        'nvidia-cusolver-cu12',
        'nvidia-cusparse-cu12',
        'nvidia-cusparselt-cu12',
        'nvidia-nccl-cu12',
        'nvidia-nvjitlink-cu12',
        'nvidia-nvtx-cu12',
        'python-dateutil',
        'requests',
        's3transfer',
        'setuptools',
        'six',
        'sympy',
        'torch',
        'tqdm',
        'triton',
        'typing_extensions',
        'urllib3'
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)