apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  selector:
    app: grafana
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 30300