apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: default
spec:
  selector:
    app: kafka-ui
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080