apiVersion: v1
kind: Service
metadata:
  name: test-frontend-service
spec:
  selector:
    app: test-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Use LoadBalancer to expose the service externally